// Writes docs/contrast.md from src/styles.css + the pairs in src/lib/design-tokens.ts.
// Run: bun scripts/contrast-report.ts   (the unit tests enforce the same pairs)
import { readFileSync, writeFileSync } from "node:fs";
import { contrastRatio } from "../src/lib/color";
import { contrastPairs, parseTokenHexes } from "../src/lib/design-tokens";

const tokens = parseTokenHexes(readFileSync("src/styles.css", "utf8"));
const hex = (name: string) => tokens.get(name)?.hex ?? "??";
const rows = contrastPairs.map(({ fg, bg, min, use }) => {
  const ratio = contrastRatio(hex(fg), hex(bg));
  return `| ${use} | \`${fg}\` ${hex(fg)} | \`${bg}\` ${hex(bg)} | ${ratio.toFixed(2)}:1 | ${min}:1 | ${ratio >= min ? "✓ pass" : "✗ FAIL"} |`;
});
writeFileSync(
  "docs/contrast.md",
  `# Contrast check (WCAG 2.x AA)

Generated by \`bun scripts/contrast-report.ts\` from \`src/styles.css\`; \`src/lib/design-tokens.test.ts\` fails CI if any pair drops below its minimum.
4.5:1 = normal text. 3:1 = large text and UI components (icons, input borders, focus rings).

| Use | Foreground | Background | Ratio | Required | Result |
|---|---|---|---|---|---|
${rows.join("\n")}

Notes:
- \`--mend-border\` (#2C2C5A) is about 1.3:1 and is only used for decorative dividers, which WCAG doesn't require to meet 3:1. Form controls use \`--mend-input-border\` (#6A6AA0) instead.
- \`--status-closed\` (#64748B) is only about 3.2–3.9:1, so it's used for icons and dots only; status labels are always \`--mend-text\`.
`,
);
console.log(`docs/contrast.md written (${rows.length} pairs)`);
