/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBoardRouteImport } from './routes/app/board'
import { Route as AppCatalogRouteImport } from './routes/app/catalog'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSetupRouteImport } from './routes/app/setup'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as TTokenRouteImport } from './routes/t/$token'
import { Route as TagTicketIdRouteImport } from './routes/tag.$ticketId'
import { Route as AppCustomersIndexRouteImport } from './routes/app/customers/index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app/customers/$customerId'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSettingsAuditRouteImport } from './routes/app/settings/audit'
import { Route as AppSettingsBoardRouteImport } from './routes/app/settings/board'
import { Route as AppSettingsMessagesRouteImport } from './routes/app/settings/messages'
import { Route as AppSettingsSecurityRouteImport } from './routes/app/settings/security'
import { Route as AppSettingsShopRouteImport } from './routes/app/settings/shop'
import { Route as AppSettingsTaxesRouteImport } from './routes/app/settings/taxes'
import { Route as AppSettingsTeamRouteImport } from './routes/app/settings/team'
import { Route as AppTicketsIndexRouteImport } from './routes/app/tickets/index'
import { Route as AppTicketsTicketIdRouteImport } from './routes/app/tickets/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTicketIdRoute = TagTicketIdRouteImport.update({
  id: '/tag/$ticketId',
  path: '/tag/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBoardRoute = AppSettingsBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMessagesRoute = AppSettingsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsShopRoute = AppSettingsShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTaxesRoute = AppSettingsTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsTicketIdRoute = AppTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/board': typeof AppBoardRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/setup': typeof AppSetupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/invite/$token': typeof InviteTokenRoute
  '/t/$token': typeof TTokenRoute
  '/tag/$ticketId': typeof TagTicketIdRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/settings/audit': typeof AppSettingsAuditRoute
  '/app/settings/board': typeof AppSettingsBoardRoute
  '/app/settings/messages': typeof AppSettingsMessagesRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/shop': typeof AppSettingsShopRoute
  '/app/settings/taxes': typeof AppSettingsTaxesRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/board': typeof AppBoardRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/setup': typeof AppSetupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/invite/$token': typeof InviteTokenRoute
  '/t/$token': typeof TTokenRoute
  '/tag/$ticketId': typeof TagTicketIdRoute
  '/app': typeof AppIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/settings/audit': typeof AppSettingsAuditRoute
  '/app/settings/board': typeof AppSettingsBoardRoute
  '/app/settings/messages': typeof AppSettingsMessagesRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/shop': typeof AppSettingsShopRoute
  '/app/settings/taxes': typeof AppSettingsTaxesRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/tickets': typeof AppTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/board': typeof AppBoardRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/setup': typeof AppSetupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/invite/$token': typeof InviteTokenRoute
  '/t/$token': typeof TTokenRoute
  '/tag/$ticketId': typeof TagTicketIdRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/settings/audit': typeof AppSettingsAuditRoute
  '/app/settings/board': typeof AppSettingsBoardRoute
  '/app/settings/messages': typeof AppSettingsMessagesRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/settings/shop': typeof AppSettingsShopRoute
  '/app/settings/taxes': typeof AppSettingsTaxesRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/tickets/': typeof AppTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/app/board'
    | '/app/catalog'
    | '/app/messages'
    | '/app/settings'
    | '/app/setup'
    | '/auth/confirm'
    | '/invite/$token'
    | '/t/$token'
    | '/tag/$ticketId'
    | '/app/'
    | '/app/customers/$customerId'
    | '/app/settings/audit'
    | '/app/settings/board'
    | '/app/settings/messages'
    | '/app/settings/security'
    | '/app/settings/shop'
    | '/app/settings/taxes'
    | '/app/settings/team'
    | '/app/tickets/$ticketId'
    | '/app/customers/'
    | '/app/settings/'
    | '/app/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/app/board'
    | '/app/catalog'
    | '/app/messages'
    | '/app/setup'
    | '/auth/confirm'
    | '/invite/$token'
    | '/t/$token'
    | '/tag/$ticketId'
    | '/app'
    | '/app/customers/$customerId'
    | '/app/settings/audit'
    | '/app/settings/board'
    | '/app/settings/messages'
    | '/app/settings/security'
    | '/app/settings/shop'
    | '/app/settings/taxes'
    | '/app/settings/team'
    | '/app/tickets/$ticketId'
    | '/app/customers'
    | '/app/settings'
    | '/app/tickets'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/mfa'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/app/board'
    | '/app/catalog'
    | '/app/messages'
    | '/app/settings'
    | '/app/setup'
    | '/auth/confirm'
    | '/invite/$token'
    | '/t/$token'
    | '/tag/$ticketId'
    | '/app/'
    | '/app/customers/$customerId'
    | '/app/settings/audit'
    | '/app/settings/board'
    | '/app/settings/messages'
    | '/app/settings/security'
    | '/app/settings/shop'
    | '/app/settings/taxes'
    | '/app/settings/team'
    | '/app/tickets/$ticketId'
    | '/app/customers/'
    | '/app/settings/'
    | '/app/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MfaRoute: typeof MfaRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  InviteTokenRoute: typeof InviteTokenRoute
  TTokenRoute: typeof TTokenRoute
  TagTicketIdRoute: typeof TagTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/board': {
      id: '/app/board'
      path: '/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$ticketId': {
      id: '/tag/$ticketId'
      path: '/tag/$ticketId'
      fullPath: '/tag/$ticketId'
      preLoaderRoute: typeof TagTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$customerId': {
      id: '/app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/audit': {
      id: '/app/settings/audit'
      path: '/audit'
      fullPath: '/app/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/board': {
      id: '/app/settings/board'
      path: '/board'
      fullPath: '/app/settings/board'
      preLoaderRoute: typeof AppSettingsBoardRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/messages': {
      id: '/app/settings/messages'
      path: '/messages'
      fullPath: '/app/settings/messages'
      preLoaderRoute: typeof AppSettingsMessagesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/shop': {
      id: '/app/settings/shop'
      path: '/shop'
      fullPath: '/app/settings/shop'
      preLoaderRoute: typeof AppSettingsShopRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/taxes': {
      id: '/app/settings/taxes'
      path: '/taxes'
      fullPath: '/app/settings/taxes'
      preLoaderRoute: typeof AppSettingsTaxesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/team': {
      id: '/app/settings/team'
      path: '/team'
      fullPath: '/app/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/tickets/': {
      id: '/app/tickets/'
      path: '/tickets'
      fullPath: '/app/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets/$ticketId': {
      id: '/app/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/app/tickets/$ticketId'
      preLoaderRoute: typeof AppTicketsTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsBoardRoute: typeof AppSettingsBoardRoute
  AppSettingsMessagesRoute: typeof AppSettingsMessagesRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsShopRoute: typeof AppSettingsShopRoute
  AppSettingsTaxesRoute: typeof AppSettingsTaxesRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsBoardRoute: AppSettingsBoardRoute,
  AppSettingsMessagesRoute: AppSettingsMessagesRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsShopRoute: AppSettingsShopRoute,
  AppSettingsTaxesRoute: AppSettingsTaxesRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppBoardRoute: typeof AppBoardRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSetupRoute: typeof AppSetupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppTicketsTicketIdRoute: typeof AppTicketsTicketIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoardRoute: AppBoardRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSetupRoute: AppSetupRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppTicketsTicketIdRoute: AppTicketsTicketIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MfaRoute: MfaRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  InviteTokenRoute: InviteTokenRoute,
  TTokenRoute: TTokenRoute,
  TagTicketIdRoute: TagTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
